name: Lint and Test Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      # - name: Run chart-testing (list-changed)
      #   id: list-changed
      #   run: |
      #     changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
      #     if [[ -n "$changed" ]]; then
      #       # echo "::set-output name=changed::true"
      #       echo "name=changed::true" >> $GITHUB_OUTPUT
      #     else
      #       # echo "::set-output name=changed::false"
      #       echo "name=changed::false" >> $GITHUB_OUTPUT
      #     fi

        # you MUST increase the version of the chart, otherwise chart-releaser will fail
      - name: Run chart-testing (lint)
        run: |
          #if [ "${{ steps.list-changed.outputs.changed }}" = true ]; then
          #  echo "checking changed charts only"
            ct lint --debug --target-branch ${{ github.event.repository.default_branch }}
          #else
          #  echo "checking ALL charts"
          #  ct lint --all --debug --target-branch ${{ github.event.repository.default_branch }}
          #fi
